### ISSUE TITLE
13 06 2022

### ISSUE THREAD

**Issue by caterinatoniolo** [kolonialno/slack-notifier#73]
- reviewed and iterated on weekly update format 
-  iterated on v0 model with new data - next  talk  to JQ about setting biweekly targets.
-  iterated  on market  strategy table of content  (to be shared with stakeholders)

Progress
Finalised local content plan and ran through with consultant
Made progress on stage gate KPIs
Started summarising all the different learning tracks for Alpha and Beta
Started collaboration with Google for pre-launch surveys
Blockers
Input from local category team (for certain test cases)

**Comment by ljodal** [comment]
Seems like this is in the wrong repo?
